create table media ("id" INTEGER PRIMARY KEY, "url" TEXT UNIQUE NOT NULL, "mime" TEXT, "info" BLOB, "opusid" INTEGER, FOREIGN KEY (opusid) REFERENCES opus(id) ON UPDATE SET NULL);
create table opus ("id" INTEGER PRIMARY KEY,  "titleid" INTEGER UNIQUE NOT NULL, "artistid" INTEGER, "otherid" INTEGER, "albumid" INTEGER, "genreid" INTEGER, FOREIGN KEY (titleid) REFERENCES word(id), FOREIGN KEY (artistid) REFERENCES artist(id) ON UPDATE SET NULL, FOREIGN KEY (albumid) REFERENCES album(id) ON UPDATE SET NULL, FOREIGN KEY (genreid) REFERENCES word(id) ON UPDATE SET NULL);
create table album ("id" INTEGER PRIMARY KEY, "wordid" INTEGER UNIQUE NOT NULL, "artistid" INTEGER, "genreid" INTEGER, FOREIGN KEY (wordid) REFERENCES word(id), FOREIGN KEY (artistid) REFERENCES artist(id) ON UPDATE SET NULL, FOREIGN KEY (genreid) REFERENCES word(id) ON UPDATE SET NULL);
create table artist ("id" INTEGER PRIMARY KEY, "wordid" INTEGER UNIQUE NOT NULL, "info" BLOB, FOREIGN KEY (wordid) REFERENCES word(id));
create table genre ("id" INTEGER PRIMARY KEY, "wordid" INTEGER, FOREIGN KEY (wordid) REFERENCES word(id));
create table word ("id" INTEGER PRIMARY KEY, "name" TEXT UNIQUE NOT NULL);
insert into "word" ("id", "name") values ( 0,"blues");
insert into "word" ("id", "name") values ( 1,"classic rock");
insert into "word" ("id", "name") values ( 2,"country");
insert into "word" ("id", "name") values ( 3,"dance");
insert into "word" ("id", "name") values ( 4,"disco");
insert into "word" ("id", "name") values ( 5,"funk");
insert into "word" ("id", "name") values ( 6,"grunge");
insert into "word" ("id", "name") values ( 7,"hip-hop");
insert into "word" ("id", "name") values ( 8,"jazz");
insert into "word" ("id", "name") values ( 9,"metal");
insert into "word" ("id", "name") values ( 10,"new age");
insert into "word" ("id", "name") values ( 11,"oldies");
insert into "word" ("id", "name") values ( 12,"other");
insert into "word" ("id", "name") values ( 13,"pop");
insert into "word" ("id", "name") values ( 14,"rnB");
insert into "word" ("id", "name") values ( 15,"rap");
insert into "word" ("id", "name") values ( 16,"reggae");
insert into "word" ("id", "name") values ( 17,"pock");
insert into "word" ("id", "name") values ( 18,"techno");
insert into "word" ("id", "name") values ( 19,"industrial");
insert into "word" ("id", "name") values ( 20,"alternative");
insert into "word" ("id", "name") values ( 21,"ska");
insert into "word" ("id", "name") values ( 22,"death metal");
insert into "word" ("id", "name") values ( 23,"pranks");
insert into "word" ("id", "name") values ( 24,"soundtrack");
insert into "word" ("id", "name") values ( 25,"euro techno");
insert into "word" ("id", "name") values ( 26,"ambient");
insert into "word" ("id", "name") values ( 27,"trip-hop");
insert into "word" ("id", "name") values ( 28,"vocal");
insert into "word" ("id", "name") values ( 29,"jazz funk");
insert into "word" ("id", "name") values ( 30,"fusion");
insert into "word" ("id", "name") values ( 31,"trance");
insert into "word" ("id", "name") values ( 32,"classical");
insert into "word" ("id", "name") values ( 33,"instrumental");
insert into "word" ("id", "name") values ( 34,"acid");
insert into "word" ("id", "name") values ( 35,"house");
insert into "word" ("id", "name") values ( 36,"game");
insert into "word" ("id", "name") values ( 37,"sample");
insert into "word" ("id", "name") values ( 38,"gospel");
insert into "word" ("id", "name") values ( 39,"noice");
insert into "word" ("id", "name") values ( 40,"alternative rock");
insert into "word" ("id", "name") values ( 41,"bass");
insert into "word" ("id", "name") values ( 42,"soul");
insert into "word" ("id", "name") values ( 43,"punk");
insert into "word" ("id", "name") values ( 44,"space");
insert into "word" ("id", "name") values ( 45,"meditative");
insert into "word" ("id", "name") values ( 46,"instrumental pop");
insert into "word" ("id", "name") values ( 47,"instrumental rock");
insert into "word" ("id", "name") values ( 48,"ehtnic");
insert into "word" ("id", "name") values ( 49,"gothic");
insert into "word" ("id", "name") values ( 50,"darkwave");
insert into "word" ("id", "name") values ( 51,"techno intdustrial");
insert into "word" ("id", "name") values ( 52,"electronic");
insert into "word" ("id", "name") values ( 53,"pop folk");
insert into "word" ("id", "name") values ( 54,"euro dance");
insert into "word" ("id", "name") values ( 55,"dream");
insert into "word" ("id", "name") values ( 56,"southern rock");
insert into "word" ("id", "name") values ( 57,"comedy");
insert into "word" ("id", "name") values ( 58,"cult");
insert into "word" ("id", "name") values ( 59,"gangsta");
insert into "word" ("id", "name") values ( 60,"top 40");
insert into "word" ("id", "name") values ( 61,"christian rap");
insert into "word" ("id", "name") values ( 62,"pop funk");
insert into "word" ("id", "name") values ( 63,"jumgle");
insert into "word" ("id", "name") values ( 64,"native US");
insert into "word" ("id", "name") values ( 65,"cabaret");
insert into "word" ("id", "name") values ( 66,"new wave");
insert into "word" ("id", "name") values ( 67,"psychedelic");
insert into "word" ("id", "name") values ( 68,"rave");
insert into "word" ("id", "name") values ( 69,"show tunes");
insert into "word" ("id", "name") values ( 70,"trailer");
insert into "word" ("id", "name") values ( 71,"lo-fi");
insert into "word" ("id", "name") values ( 72,"tribal");
insert into "word" ("id", "name") values ( 73,"acid punk");
insert into "word" ("id", "name") values ( 74,"acid jazz");
insert into "word" ("id", "name") values ( 75,"polka");
insert into "word" ("id", "name") values ( 76,"retro");
insert into "word" ("id", "name") values ( 77,"musical");
insert into "word" ("id", "name") values ( 78,"rock'n'roll");
insert into "word" ("id", "name") values ( 79,"hard rock");
insert into "genre" ("id", "wordid") values ( 0, 0);
insert into "genre" ("id", "wordid") values ( 1, 1);
insert into "genre" ("id", "wordid") values ( 2, 2);
insert into "genre" ("id", "wordid") values ( 3, 3);
insert into "genre" ("id", "wordid") values ( 4, 4);
insert into "genre" ("id", "wordid") values ( 5, 5);
insert into "genre" ("id", "wordid") values ( 6, 6);
insert into "genre" ("id", "wordid") values ( 7, 7);
insert into "genre" ("id", "wordid") values ( 8, 8);
insert into "genre" ("id", "wordid") values ( 9, 9);
insert into "genre" ("id", "wordid") values ( 10, 10);
insert into "genre" ("id", "wordid") values ( 11, 11);
insert into "genre" ("id", "wordid") values ( 12, 12);
insert into "genre" ("id", "wordid") values ( 13, 13);
insert into "genre" ("id", "wordid") values ( 14, 14);
insert into "genre" ("id", "wordid") values ( 15, 15);
insert into "genre" ("id", "wordid") values ( 16, 16);
insert into "genre" ("id", "wordid") values ( 17, 17);
insert into "genre" ("id", "wordid") values ( 18, 18);
insert into "genre" ("id", "wordid") values ( 19, 19);
insert into "genre" ("id", "wordid") values ( 20, 20);
insert into "genre" ("id", "wordid") values ( 21, 21);
insert into "genre" ("id", "wordid") values ( 22, 22);
insert into "genre" ("id", "wordid") values ( 23, 23);
insert into "genre" ("id", "wordid") values ( 24, 24);
insert into "genre" ("id", "wordid") values ( 25, 25);
insert into "genre" ("id", "wordid") values ( 26, 26);
insert into "genre" ("id", "wordid") values ( 27, 27);
insert into "genre" ("id", "wordid") values ( 28, 28);
insert into "genre" ("id", "wordid") values ( 29, 29);
insert into "genre" ("id", "wordid") values ( 30, 30);
insert into "genre" ("id", "wordid") values ( 31, 31);
insert into "genre" ("id", "wordid") values ( 32, 32);
insert into "genre" ("id", "wordid") values ( 33, 33);
insert into "genre" ("id", "wordid") values ( 34, 34);
insert into "genre" ("id", "wordid") values ( 35, 35);
insert into "genre" ("id", "wordid") values ( 36, 36);
insert into "genre" ("id", "wordid") values ( 37, 37);
insert into "genre" ("id", "wordid") values ( 38, 38);
insert into "genre" ("id", "wordid") values ( 39, 39);
insert into "genre" ("id", "wordid") values ( 40, 40);
insert into "genre" ("id", "wordid") values ( 41, 41);
insert into "genre" ("id", "wordid") values ( 42, 42);
insert into "genre" ("id", "wordid") values ( 43, 43);
insert into "genre" ("id", "wordid") values ( 44, 44);
insert into "genre" ("id", "wordid") values ( 45, 45);
insert into "genre" ("id", "wordid") values ( 46, 46);
insert into "genre" ("id", "wordid") values ( 47, 47);
insert into "genre" ("id", "wordid") values ( 48, 48);
insert into "genre" ("id", "wordid") values ( 49, 49);
insert into "genre" ("id", "wordid") values ( 50, 50);
insert into "genre" ("id", "wordid") values ( 51, 51);
insert into "genre" ("id", "wordid") values ( 52, 52);
insert into "genre" ("id", "wordid") values ( 53, 53);
insert into "genre" ("id", "wordid") values ( 54, 54);
insert into "genre" ("id", "wordid") values ( 55, 55);
insert into "genre" ("id", "wordid") values ( 56, 56);
insert into "genre" ("id", "wordid") values ( 57, 57);
insert into "genre" ("id", "wordid") values ( 58, 58);
insert into "genre" ("id", "wordid") values ( 59, 59);
insert into "genre" ("id", "wordid") values ( 60, 60);
insert into "genre" ("id", "wordid") values ( 61, 61);
insert into "genre" ("id", "wordid") values ( 62, 62);
insert into "genre" ("id", "wordid") values ( 63, 63);
insert into "genre" ("id", "wordid") values ( 64, 64);
insert into "genre" ("id", "wordid") values ( 65, 65);
insert into "genre" ("id", "wordid") values ( 66, 66);
insert into "genre" ("id", "wordid") values ( 67, 67);
insert into "genre" ("id", "wordid") values ( 68, 68);
insert into "genre" ("id", "wordid") values ( 69, 69);
insert into "genre" ("id", "wordid") values ( 70, 70);
insert into "genre" ("id", "wordid") values ( 71, 71);
insert into "genre" ("id", "wordid") values ( 72, 72);
insert into "genre" ("id", "wordid") values ( 73, 73);
insert into "genre" ("id", "wordid") values ( 74, 74);
insert into "genre" ("id", "wordid") values ( 75, 75);
insert into "genre" ("id", "wordid") values ( 76, 76);
insert into "genre" ("id", "wordid") values ( 77, 77);
insert into "genre" ("id", "wordid") values ( 78, 78);
insert into "genre" ("id", "wordid") values ( 79, 79);
